---
- hosts: all

  vars:
    applications:
      - firefox
      - google-chrome
      - gpgtools
      - hipchat
      - robomongo
      - sequel-pro
      - the-unarchiver
      - transmit
      - vagrant
      - virtualbox
      - vlc
    application_dir: /Users/gurhget/Applications
    brews:
      - ack
      - ant
      - chromedriver
      - emacs
      - h2
      - ivy
      - lynx
      - markdown
      - python
      - scala
      - tree
      - rsync
      - wget
      - zsh
    caskroom_dir: /usr/local/caskroom
    dotfiles_dir: /Users/craig/Code/dotfiles
    email: gurghet@gmail.com
    github_username: gurghet
    home_dir: /Users/gurghet
    name: Andrea Passaglia
    zsh_path: /usr/local/bin/zsh

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
    - include: tasks/zsh.yml tags=zsh
    - include: tasks/dotfiles.yml tags=dotfiles
